### PR TITLE
chore: placeholders on inputs and textareas disappear on focus

### PR DESCRIPTION
**Pull request by sally**
This addresses Issue #49 

- placeholders on inputs and textarea elements disappear on focus/active
- increased border width on input and textarea elements on focus/active

### CODE REVIEW

**Comment by atharva3010** [comment]
@sally you’d need to enable other options for borderWidth too, the options which you have put there will override the default ones.

**Comment by atharva3010** [comment]
https://tailwindcss.com/docs/configuring-variants/

**Comment by sally** [comment]
@atharva3010 Totally right, should be fixed now. I added `'responsive'`

image

**Comment by atharva3010** [comment]
Thank you! Oh and ‘hover’ too

**Comment by sally** [comment]
@atharva3010 Alright, I added hover and squashed it into my previous commit dealing with adding default variants

**Pull request merged**
