### PR TITLE
feat: checkout progress nav refresh (partial)

### PR DESCRIPTION
**Pull request by sally**
This partially addresses Issue #97 

In this PR, we change the stepper top bar to be a circular progress bar with no navigation components. We also change the bottom progress buttons to be nav buttons allowing the user to go back.

In future PRs we will complete treating #97 with animations and other loose ends.

image

### CODE REVIEW

**Comment by paulchrisluke** [comment]
This is beautiful. Can the bottom progress buttons stay fixed bottom on mobile? I'm trying to avoid the sensation of the page jumping around.

**Comment by sally** [comment]
@paulchrisluke should be working now. I originally planned to make them sticky in a separate PR but it ended up being pretty straightforward.
image5

Animations for the checkout procedure will definitely be in a separate PR though.

**Comment by paulchrisluke** [comment]
Looks great! Approved 👍🏾

**Comment by atharva3010** [comment]
@sally Looks great! Love the stepper nav and buttons!

It’d be super amazing to abstract the buttons into a component so that it can be easily reused across forms instead of copy pasting it.
You can take clue from the existing button component and replicate the same process. We can make a single button and use it for both, back and forward steps. A full width button, the width of which is controlled by the parent component. So you could stack two buttons like these and prevent WET.

**Comment by sally** [comment]
@atharva3010 Agree. This branch now has a CheckoutNavBar component which the 5 form components use.

**Comment by sally** [comment]
@atharva3010 One thing I wanted to do is pull CheckoutNavBar component up to CheckoutForm so that there would only be one instance of CheckoutNavBar instead of 5 in the different form pages. However, I couldn't really figure out how to validate the forms properly if I did that.

**Comment by atharva3010** [comment]
@sally I guess we could emit the keys we use to validate, from each form, when values change. But, I would not decouple the buttons from individual forms, right now I trigger different API calls/functions at each step, there wouldn't be any clean way to do that too.

Let's keep it the way it is.
Thank you for your help @sally! really appreciate it.

**Pull request merged**
