### PR TITLE
User location finder

### PR DESCRIPTION
**Pull request by abdullahcalisir12**
# Issue Being Addressed
#264 
Put the issue(s) # that your PR is addressing here. e.g. #15, #29

# Type of PR

Put an `x` in the brackets for the type(s) of PR this is. You may tick more than one.

[ ] Bug Fix
[x] Refactor
[ ] New Feature
[ ] Update to Existing Feature
[ ] Other (state below)

# Description

**For Bug Fixes:** What was the root cause? How do your changes fix the bug effectively?

**For Refactors:** What are we refactoring and why? How do your changes address this need for refactoring?
User location finder component created to imitate tinder-like behavior . And refactored customer address respectively. 
**For New Features:** What feature are we adding? Explain your technical approach to doing this.

**For Feature Updates:** What feature are we updating? Explain your technical approach to doing this.

**For Other:** State what 'type' of PR yours is and elaborate on the PR's technical content.

# How to Test/Reproduce

Provide steps on how one can test your changes here. e.g.
1. Go to home page https://deploy-preview-288--foodouken.netlify.app/
2. Add some items to cart
4. Click order button
5. Fill first step and click next to go to customer address
6. Test location completely

# Screenshots/casts

If applicable, include any relevant screenshot or screencasts of your changes.
image

# Additional Context
@bamboochow I need some text to notify user. Like if user blocked it's location go and open from browser settings. 
and for the possible error. Something happened and we couldn't take your location from the provider. Please enter your address manually. 
And one for if location from provider is not correct location of user
Provide any additional notes that you think would help effective review of your code.

### CODE REVIEW

**Comment by bamboochow** [comment]
@abdullahcalisir12 
Title: Oops!
Text: You need to enable location sharing to use Foodouken. Visit your browser settings. 
Button: Find Out how (Leads to https://www.computerhope.com/issues/ch001918.htm) 
image

**Comment by bamboochow** [comment]
@abdullahcalisir12
H3 Title: Oops!
Text: There was a problem finding you. Please enter address manually.
Button: ENTER ADDRESS MANUALLY (Closes popup) 

image

**Comment by abdullahcalisir12** [comment]
@bamboochow @paulchrisluke PR is updated.

**Comment by bamboochow** [comment]
If you can just fix "Opps!" to "Oops!" real quick....
image0

And this might be a better article to link to. 
https://docs.buddypunch.com/en/articles/919258-how-to-enable-location-services-for-chrome-safari-and-android-ios-devices-gps-setting

**Pull request merged**
