### PR TITLE
fix input tap ios

### PR DESCRIPTION
**Pull request by mort3za**
Adding v-click-outside is the source of this bug in iOS. Removing it from Dropdown.vue, seems fixes the problem.

### CODE REVIEW

**Comment by atharva3010** [comment]
Hmm, but we need to use v-click-outside to close the dropdown upon clicking outside.

Is there a way we can make them both work?

**Comment by mort3za** [comment]
@atharva3010 try implementing it manually, it should not be hard. if that worked without this bug on iOS then open an issue on v-click-outside github repo.

**Comment by atharva3010** [comment]
Yeah, I’ll likely make a directive myself

**Comment by atharva3010** [comment]
Fixes #278

**Pull request merged**
