### PR TITLE
Google Maps draggable pin for exact customer coords

### PR DESCRIPTION
**Pull request by joeelia**
# Issue Being Addressed

None. I heard Chris mention he wanted this in his stream so I decided to try it.

# Type of PR

[x] New Feature

# Description

Removed the Google Map iFrame and replaced it with [vue-google-maps](https://github.com/xkjyeah/vue-google-maps)

# How to Test/Reproduce

Provide steps on how one can test your changes here. e.g.
1. Go to https://deploy-preview-323--foodouken.netlify.app/
2. Add item to cart. Enter your information to get to step 2
3. On Step 2 Share Your Location and Drag Pin / map around
4. Customer sets their exact coordinates with pin drop

# Screenshots/casts

https://streamable.com/zsjd3d

# Additional Context

Giving GPS data isn't exact enough. Allowing user to set their exact location minimizes delivery issues.

### CODE REVIEW

**Comment by paulchrisluke** [comment]
I'm hung on this step on desktop chrome after I select my location:

https://deploy-preview-323--foodouken.netlify.app/shop/angkor-tacos/delivery-time

image

**Comment by joeelia** [comment]
Pretty sure I addressed that issue of getting stuck at delivery time in the discord. It’s not an issue with this PR. Try testing again, but with a tenant that has their hours setup correctly in staging.

**Comment by atharva3010** [comment]
Check if you are updating the user's google maps location Url string with the coordinates received from the map

**Comment by paulchrisluke** [comment]
iphone chrome gets stuck here:

image

**Pull request merged**
