### PR TITLE
feat: add transitions and spinners while category loads

### PR DESCRIPTION
**Pull request by sally**
When we switch between categories, we show the loading "spinner" component. We also add fade transitions between spinner and category components to make for a smoother experience.

### CODE REVIEW

**Comment by sally** [comment]
Note: If your categories are loading too fast to adequately test this, you can use `setTimeout` in the Category store where we set `loading` to false to simulate a longer load time.

**Comment by atharva3010** [comment]
Can we add the transition to the main app load too?

**Comment by sally** [comment]
@atharva3010 Though it is subtle since the fade in is done in 0.3 seconds, it should be working on main app load now as requested.

**Comment by atharva3010** [comment]
I think I see the home screen before the loader comes up. hmm

**Comment by sally** [comment]
@atharva3010 Setting `loading`'s initial value should fix this bug, as we discussed in Discord

**Comment by atharva3010** [comment]
Thank you, merging this.

**Pull request merged**
