### PR TITLE
chore: update button component style and usage instances

### PR DESCRIPTION
**Pull request by sally**
This addresses Issue #109 

We update the Button component's styles. We update Button component usage instances accordingly.

### CODE REVIEW

**Comment by atharva3010** [comment]
image  
  
Should we make the button full width on desktop too? Since it's already full width when the checkout process starts, the small button looks a bit weird in the start.

**Comment by atharva3010** [comment]
Also, instead of defining each class as an individual prop, we can set `inheritAttrs: false` and then whatever class you give to the component, it will be applied to the root element of the child component as normal classes.

You can read more about it here: https://vuejs.org/v2/api/#inheritAttrs

**Comment by sally** [comment]
@atharva3010 Thanks for the feedback. I made some changes to make the Button component less cluttered with props related to CS classes.

I did leave one such prop in there - `width`.  To make the buttons full width by default, I tried putting `w-full` in the Button component's root element. However, it conflicted with `flex-grow` which was a class we wanted to pass down sometimes. (Even when passing down `w-auto flex-grow` instead of just `flex-grow`, the `w-full` on the Button component root element would override the `w-auto` which was passed.)

So, I just kept `width` a prop which is `w-full` by default and included it in the Button component's root element.

**Comment by atharva3010** [comment]
Looks great @sally Merging this! Thank you.

**Pull request merged**
