### PR TITLE
Created a small cookie utility and added X svg button to dismiss banner

### PR DESCRIPTION
**Pull request by joeelia**
# Issue Being Addressed

None

# Type of PR

Put an `x` in the brackets for the type(s) of PR this is. You may tick more than one.

[x] Update to Existing Feature

# Description

Give user the ability to dismiss the beta banner if they want

# How to Test/Reproduce

Provide steps on how one can test your changes here. e.g.
1. Go to https://deploy-preview-319--foodouken.netlify.app/
2. Notice the banner has an 'x' on top right. Click it.
3. Notice banner is gone and does not show on any subsequent views

# Screenshots/casts

Screen Shot 2020-07-09 at 7 19 01 PM

# Additional Context

The banner will come back after 7 days. This duration can be extended, but I think 7 days is good to start with.

### CODE REVIEW

**Comment by paulchrisluke** [comment]
center aligned top/bottom please!

**Comment by joeelia** [comment]
I centered the 'x' and added hover effect and quick 200ms transition effect when dismissing the banner

**Comment by mort3za** [comment]
Is there any benefit in using cookie? Why you don't use localStorage which is simpler?

**Comment by joeelia** [comment]
@mort3za localStorage data does not expire. With a cookie the message will come back after 7 days then they will have to dismiss it again and repeat. I think the beta banner should continue to show every 7 days until it's removed.

**Pull request merged**
