### PR TITLE
Implement empty menu state

### PR DESCRIPTION
**Pull request by lloydjatkinson**
# Issue Being Addressed
#266 
# Type of PR

Put an `x` in the brackets for the type(s) of PR this is. You may tick more than one.

[ ] Bug Fix
[ ] Refactor
[x ] New Feature
[ ] Update to Existing Feature
[ ] Other (state below)

# Description

A new empty state was required for the category and item menus. This is to make it super clear to the user. This was implemented by creating a `<MenuEmptyState>` component with slots. This component is then used in both the category and item menus. It is only shown when the user has not configured any categories or items. In both usages of the new component a `<RouterLink>` component with slot usage is used.

# How to Test/Reproduce

Provide steps on how one can test your changes here. e.g.
1. Open a restaurant with no categories (or delete existing ones) and the new empty state component will be displayed
2. Either click the action button or the top right plus icon button to create a new category.
3. Upon returning to the category menu the empty state component will no longer be displayed and the category list will be displayed instead
4. Repeat the same process for items under a category

# Screenshots/casts

If applicable, include any relevant screenshot or screencasts of your changes.
image
image

### CODE REVIEW

**Comment by lloydjatkinson** [comment]
I had a look at the those classes in typography.css but it doesn't have the `font-family: Open Sans;` property - also should I still use utility classes for the spacing between the H1 and H2 for example?

Also, the only + icon without a circle in assets is a slightly green PNG, shall I make a new icon?

**Comment by lloydjatkinson** [comment]
Here is the latest styling. Two things to note:

- No plain + icon file so I went for using the + symbol
- Had a look at using the undraw empty image we discussed but there's a couple of problems with that - firstly the PNG's from undraw are all white background not transparent, and secondly when using the SVG version the SVG is consistently being rendered 50% to the right - not sure if this is a view box or vue-svg-loader problem.

image

**Comment by paulchrisluke** [comment]
button text is smaller and bold @atharva3010 where do we find the text classes? 
image

**Comment by atharva3010** [comment]
Text classes are present in typography.css
font-family: Open sans is default.

**Comment by mort3za** [comment]
Because foodouken already has it's own title bar implementation, ignore the WithTitleBar layout, we need to add just LayoutSplash.

**Comment by lloydjatkinson** [comment]
@mort3za The MenuEmptyState component could be renamed and moved somewhere else:

```vue
<template>
  <div class="bottom-0 flex flex-col items-center">
    <slot name="image">
      <img class="w-40 m-auto mb-6 md:w-64" :src="Hadooken" />
    </slot>
    <h1 class="mb-4 tg-h1-mobile">
      <slot name="heading"></slot>
    </h1>
    <h2 class="mb-8 tg-body-mobile">
      <slot name="description"></slot>
    </h2>
    <slot name="action"></slot>
  </div>
</template>

<script>
import Hadooken from '@/assets/hadooken.png';
import Plus from '@/assets/plus.png';
import Button from '@/components/Button.vue';
export default {
  name: 'MenuItemEmptyState',
  data() {
    return {
      Hadooken,
      Plus,
      Button
    };
  }
};
</script>
```

**Comment by mort3za** [comment]
Because we want to keep projects similar as possible, please use those links I've sent.  
Specially these are layout files that we'll use them in many places.

**Pull request closed without merging**
