### PR TITLE
Issue 336

### PR DESCRIPTION
**Pull request by giteshk11**
# Issue Being Addressed

Put the issue(s) # that your PR is addressing here. e.g. #15, #29

#336 

Put an `x` in the brackets for the type(s) of PR this is. You may tick more than one.

[x] Bug Fix
[ ] Refactor
[ ] New Feature
[ ] Update to Existing Feature
[ ] Other (state below)

# Description

**For Bug Fixes:** What was the root cause? How do your changes fix the bug effectively?

**For Refactors:** What are we refactoring and why? How do your changes address this need for refactoring?

**For New Features:** What feature are we adding? Explain your technical approach to doing this.

**For Feature Updates:** What feature are we updating? Explain your technical approach to doing this.

**For Other:** State what 'type' of PR yours is and elaborate on the PR's technical content.

# How to Test/Reproduce

Provide steps on how one can test your changes here. e.g.
1. Log in as '...'
2. Go to '...'
3. Click on '...'
4. See the updated element x

# Screenshots/casts

If applicable, include any relevant screenshot or screencasts of your changes.

# Additional Context

Provide any additional notes that you think would help effective review of your code.

### CODE REVIEW

**Comment by abdullahcalisir12** [comment]
@giteshk11 there is conflict at tenant.js can you solve it? and you have same changes here #351 may I ask why did you create another PR?

**Comment by giteshk11** [comment]
these changes are different, it was opened 4 days ago

**Comment by mort3za** [comment]
Checkout the changes of `tenant.js` to staging (git checkout staging path/to/tenant.js), the new code has fixed the multi-tenant problem.

**Comment by abdullahcalisir12** [comment]
closes because has same changes on #351

**Pull request closed without merging**
